In [36]:
import pandas as pd

products = pd.read_csv("../data/product_info.csv")
products.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [37]:
reviews_1 = pd.read_csv("../data/reviews_0-250.csv")
reviews_2 = pd.read_csv("../data/reviews_250-500.csv")
reviews_3 = pd.read_csv("../data/reviews_500-750.csv")
reviews_4 = pd.read_csv("../data/reviews_750-1250.csv")
reviews_5 = pd.read_csv("../data/reviews_1250-end.csv")

reviews = pd.concat([reviews_1, reviews_2, reviews_3, reviews_4, reviews_5], ignore_index=True)

reviews.head()

/var/folders/1k/bsvhbsyn1gn8zm9g3p5pzyrc0000gn/T/ipykernel_59307/2750288550.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_1 = pd.read_csv("../data/reviews_0-250.csv")
/var/folders/1k/bsvhbsyn1gn8zm9g3p5pzyrc0000gn/T/ipykernel_59307/2750288550.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_4 = pd.read_csv("../data/reviews_750-1250.csv")
/var/folders/1k/bsvhbsyn1gn8zm9g3p5pzyrc0000gn/T/ipykernel_59307/2750288550.py:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  reviews_5 = pd.read_csv("../data/reviews_1250-end.csv")

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2,2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,light,brown,dry,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
3,3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,NaN,brown,combination,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4,4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,light,hazel,combination,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [38]:
products.shape

(8494, 27)

In [39]:
reviews.shape

(1094411, 19)

In [40]:
products.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [41]:
reviews.columns

Index(['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness',
       'total_feedback_count', 'total_neg_feedback_count',
       'total_pos_feedback_count', 'submission_time', 'review_text',
       'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color',
       'product_id', 'product_name', 'brand_name', 'price_usd'],
      dtype='object')

In [42]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8494 entries, 0 to 8493
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          8494 non-null   object
 1   product_name        8494 non-null   object
 2   brand_id            8494 non-null   int64
 3   brand_name          8494 non-null   object
 4   loves_count         8494 non-null   int64
 5   rating              8216 non-null   float64
 6   reviews             8216 non-null   float64
 7   size                6863 non-null   object
 8   variation_type      7050 non-null   object
 9   variation_value     6896 non-null   object
 10  variation_desc      1250 non-null   object
 11  ingredients         7549 non-null   object
 12  price_usd           8494 non-null   float64
 13  value_price_usd     451 non-null    float64
 14  sale_price_usd      270 non-null    float64
 15  limited_edition     8494 non-null   int64
 16  new                 8494 non-null   int64
 17  online_only         8494 non-null   int64
 18  out_of_stock        8494 non-null   int64
 19  sephora_exclusive   8494 non-null   int64
 20  highlights          6287 non-null   object
 21  primary_category    8494 non-null   object
 22  secondary_category  8486 non-null   object
 23  tertiary_category   7504 non-null   object
 24  child_count         8494 non-null   int64
 25  child_max_price     2754 non-null   float64
 26  child_min_price     2754 non-null   float64
dtypes: float64(7), int64(8), object(12)
memory usage: 1.7+ MB

In [43]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094411 entries, 0 to 1094410
Data columns (total 19 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   Unnamed: 0                1094411 non-null  int64
 1   author_id                 1094411 non-null  object
 2   rating                    1094411 non-null  int64
 3   is_recommended            926423 non-null   float64
 4   helpfulness               532819 non-null   float64
 5   total_feedback_count      1094411 non-null  int64
 6   total_neg_feedback_count  1094411 non-null  int64
 7   total_pos_feedback_count  1094411 non-null  int64
 8   submission_time           1094411 non-null  object
 9   review_text               1092967 non-null  object
 10  review_title              783757 non-null   object
 11  skin_tone                 923872 non-null   object
 12  eye_color                 884783 non-null   object
 13  skin_type                 982854 non-null   object
 14  hair_color                867643 non-null   object
 15  product_id                1094411 non-null  object
 16  product_name              1094411 non-null  object
 17  brand_name                1094411 non-null  object
 18  price_usd                 1094411 non-null  float64
dtypes: float64(3), int64(5), object(11)
memory usage: 158.6+ MB

In [44]:
reviews = reviews.drop(columns=["Unnamed: 0"])

In [45]:
df = pd.merge(reviews, products, on="product_id", how="left")

In [46]:
df.shape

(1094411, 44)

In [47]:
df.head()

,author_id,rating_x,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,...,1,0,0,['Clean at Sephora'],Skincare,Cleansers,NaN,0,NaN,NaN
1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0
2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0
3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0
4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,...,0,0,1,"['allure 2019 Best of Beauty Award Winner', 'C...",Skincare,Lip Balms & Treatments,NaN,3,24.0,24.0

In [48]:
df.columns

Index(['author_id', 'rating_x', 'is_recommended', 'helpfulness',
       'total_feedback_count', 'total_neg_feedback_count',
       'total_pos_feedback_count', 'submission_time', 'review_text',
       'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color',
       'product_id', 'product_name_x', 'brand_name_x', 'price_usd_x',
       'product_name_y', 'brand_id', 'brand_name_y', 'loves_count', 'rating_y',
       'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd_y', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [49]:
#her iki datasetten gelen aynı sütunlar
[col for col in df.columns if "_x" in col or "_y" in col]

['rating_x',
 'product_name_x',
 'brand_name_x',
 'price_usd_x',
 'product_name_y',
 'brand_name_y',
 'rating_y',
 'price_usd_y']

In [50]:
df = df.rename(columns={
    "rating_x": "rating",
    "product_name_x": "product_name",
    "brand_name_x": "brand_name",
    "price_usd_x": "price_usd"
})

df = df.drop(columns=[
    "rating_y",
    "product_name_y",
    "brand_name_y",
    "price_usd_y"
])

In [51]:
[col for col in df.columns if "_x" in col or "_y" in col]

[]

In [52]:
df.isnull().sum().sort_values(ascending=False)

variation_desc              1086128
sale_price_usd              1084658
value_price_usd             1063534
child_max_price              641008
child_min_price              641008
helpfulness                  561592
review_title                 310654
hair_color                   226768
eye_color                    209628
skin_tone                    170539
is_recommended               167988
tertiary_category            161256
highlights                   113936
skin_type                    111557
variation_value               63433
variation_type                51455
size                          43363
ingredients                   22025
review_text                    1444
limited_edition                   0
child_count                       0
new                               0
online_only                       0
out_of_stock                      0
primary_category                  0
secondary_category                0
sephora_exclusive                 0
author_id                         0
rating                            0
loves_count                       0
brand_id                          0
price_usd                         0
brand_name                        0
product_name                      0
product_id                        0
submission_time                   0
total_pos_feedback_count          0
total_neg_feedback_count          0
total_feedback_count              0
reviews                           0
dtype: int64

In [53]:
drop_cols = [
    "variation_desc",
    "sale_price_usd",
    "value_price_usd",
    "child_max_price",
    "child_min_price"
]

df = df.drop(columns=drop_cols)

In [54]:
df_clean = df
df_clean = df_clean.dropna(subset=["review_text"])

In [55]:
df_clean["review_text"].apply(len).describe()

count    1.092967e+06
mean     3.205771e+02
std      2.314448e+02
min      8.000000e+00
25%      1.720000e+02
50%      2.630000e+02
75%      4.020000e+02
max      6.448000e+03
Name: review_text, dtype: float64

In [56]:
(df_clean["review_text"].apply(len) > 1000).sum()

20753

In [57]:
#Yorum uzunluğu incelendiğinde 1000 karakter üzeri yorumların oranı yaklaşık %1.7 
#oran düşük olduğu için veri kaybını önlemek adına outlier'lar şimdilik korunmuştur.
(df_clean["review_text"].apply(len) > 1000).mean()

0.01898776449792171

In [58]:
df_clean.duplicated().sum()

224

In [59]:
df_clean = df_clean.drop_duplicates()

In [60]:
df_clean["rating"].describe()
#Ortalama rating: ~4.3 --> çoğu kişi recommend ediyor --> dataset pozitif biaslı

count    1.092743e+06
mean     4.299071e+00
std      1.149332e+00
min      1.000000e+00
25%      4.000000e+00
50%      5.000000e+00
75%      5.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [61]:
df_clean["is_recommended"].value_counts()
#positive biased

is_recommended
1.0    776866
0.0    148004
Name: count, dtype: int64

In [62]:
#text cleaning
df_clean["review_text"] = df_clean["review_text"].str.lower()
df_clean["review_text"] = df_clean["review_text"].str.replace(r"[^\w\s]", "", regex=True)

In [63]:
#word_count feature
#model şunu öğrenebilir: uzun yorum → daha detaylı → daha güvenilir / kısa yorum → belki düşük kalite
df_clean["word_count"] = df_clean["review_text"].apply(lambda x: len(x.split()))

In [64]:
df_clean[["review_text", "word_count"]].head()

                                         review_text  word_count
0  i use this with the nudestix citrus clean balm...          78
1  i bought this lip mask after reading the revie...          28
2  my review title says it all i get so excited t...          53
3  ive always loved this formula for a long time ...          45
4  if you have dry cracked lips this is a must ha...          46

In [65]:
df_clean.groupby("is_recommended")["word_count"].mean()

is_recommended
0.0    58.882780
1.0    59.951864
Name: word_count, dtype: float64

In [66]:
#feature anlamsız
df_clean = df_clean.drop(columns=["word_count"])

In [67]:
#rating_category feature
def rating_cat(x):
    if x >= 4:
        return "positive"
    elif x == 3:
        return "neutral"
    else:
        return "negative"

df_clean["rating_category"] = df_clean["rating"].apply(rating_cat)

In [68]:
df_clean["rating_category"].value_counts()

rating_category
positive    896943
negative    114051
neutral      81749
Name: count, dtype: int64

In [71]:
import os

os.makedirs("../data/processed", exist_ok=True)

df_clean.to_csv("../data/processed/sephora_clean.csv", index=False)